Make MixinItemRenderer_FixInstantItemSwitch ClientMixin instead of Common
fix
```

[20:41:14] [main/TRACE] [mixin/]: catching
java.lang.RuntimeException: Attempted to load class bly for invalid side SERVER
	at Launch//cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
	at Launch//makamys.coretweaks.optimization.transformerproxy.TransformerProxy.invokeNextHandler(TransformerProxy.java:44) ~[coretweaks-0.3.3.7-GTNH.jar:?]
	at Launch//makamys.coretweaks.optimization.ForgeFastWildcardTransformers$PatternConditionalTransformerWrapper.wrapTransform(ForgeFastWildcardTransformers.java:53) ~[coretweaks-0.3.3.7-GTNH.jar:?]
	at Launch//makamys.coretweaks.optimization.transformerproxy.TransformerProxy.invokeNextHandler(TransformerProxy.java:46) ~[coretweaks-0.3.3.7-GTNH.jar:?]
	at Launch//makamys.coretweaks.optimization.transformercache.lite.CachedTransformerWrapper.wrapTransform(CachedTransformerWrapper.java:24) ~[coretweaks-0.3.3.7-GTNH.jar:?]
	at Launch//makamys.coretweaks.optimization.transformerproxy.TransformerProxy.invokeNextHandler(TransformerProxy.java:46) ~[coretweaks-0.3.3.7-GTNH.jar:?]
	at Launch//makamys.coretweaks.optimization.transformerproxy.TransformerProxy.transform(TransformerProxy.java:27) ~[coretweaks-0.3.3.7-GTNH.jar:?]
	at System//org.spongepowered.asm.service.mojang.LegacyTransformerHandle.transformClassBytes(LegacyTransformerHandle.java:80) ~[+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.applyTransformers(MixinServiceLaunchWrapper.java:562) ~[+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassBytes(MixinServiceLaunchWrapper.java:528) ~[+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper.getClassNode(MixinServiceLaunchWrapper.java:624) ~[+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:2029) [+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1017) [+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1007) [+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:895) [+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:950) [+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:858) [+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) [+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [+unimixins-all-1.7.10-0.1.23.jar:0.15.4+mixin.0.8.7]
	at System//net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:409) [LaunchClassLoader.class:?]
	at System//net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:293) [LaunchClassLoader.class:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:557) [?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490) [?:?]
	at java.base/java.lang.Class.forName0(Native Method) [?:?]
	at java.base/java.lang.Class.forName(Class.java:547) [?:?]
	at System//net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:248) [Launch.class:?]
	at System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35) [Launch.class:?]
	at System//net.minecraft.launchwrapper.Launch.main(Launch.java:60) [Launch.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:565) ~[?:?]
	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:207) [lwjgl3ify-forgePatches.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:565) ~[?:?]
	at System//me.eigenraven.lwjgl3ify.rfb.entry.ServerMain.run(ServerMain.java:37) [lwjgl3ify-forgePatches.jar:?]
	at System//me.eigenraven.lwjgl3ify.rfb.entry.ServerMain.main(ServerMain.java:12) [lwjgl3ify-forgePatches.jar:?]
[20:41:14] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/ItemRenderer (java.lang.RuntimeException: Attempted to load class bly for invalid side SERVER)

```